package com.example.pollai.magazzino;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class AccessoAlMagazzinoTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void accessoAlMagazzino() {
        driver.get("http://localhost:8080/login-page");
        driver.manage().window().setSize(new Dimension(1936, 1056));
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("t.s1@test.com");
        driver.findElement(By.id("password")).sendKeys("!Selenium1");
        driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
        driver.findElement(By.linkText("Warehouse")).click();
        driver.findElement(By.cssSelector(".content-container")).click();
        assertThat(driver.findElement(By.cssSelector(".intro-text")).getText(), is("This is the warehouse of Selenium"));
        driver.findElement(By.cssSelector(".content-container")).click();
    }
}

