package com.example.pollai.magazzino;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InserimentoFarmacoTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void inserimentoFarmaco() {
        driver.get("http://localhost:8080/login-page");
        driver.manage().window().setSize(new Dimension(1936, 1056));
        driver.findElement(By.id("email")).sendKeys("t.s3@test.com");
        driver.findElement(By.id("password")).sendKeys("!Selenium3");
        driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
        driver.findElement(By.linkText("Warehouse")).click();
        driver.findElement(By.id("tipo_c")).click();
        driver.findElement(By.id("tipo_c")).sendKeys("Gallinamicina P");
        driver.findElement(By.id("quantita_c")).click();
        driver.findElement(By.id("quantita_c")).sendKeys("50");
        driver.findElement(By.cssSelector("form:nth-child(5) button")).click();
        driver.findElement(By.id("tipo_c")).click();
        driver.findElement(By.id("tipo_c")).sendKeys("Gallinamicina");
        driver.findElement(By.id("quantita_c")).sendKeys("50");
        driver.findElement(By.cssSelector("form:nth-child(5) button")).click();
        driver.findElement(By.cssSelector("li:nth-child(1)")).click();
        assertThat(driver.findElement(By.cssSelector("li:nth-child(1) > span:nth-child(2)")).getText(), is("50"));
        driver.findElement(By.cssSelector("li:nth-child(2)")).click();
        assertThat(driver.findElement(By.cssSelector("li:nth-child(2) > span:nth-child(2)")).getText(), is("50"));
        driver.findElement(By.cssSelector(".content-container")).click();
        driver.findElement(By.cssSelector("li:nth-child(1) > form:nth-child(3) button")).click();
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    }
}

