package com.example.pollai.magazzino;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ModificaDatiTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void modificaDati() {
        driver.get("http://localhost:8080/login-page");
        driver.manage().window().setSize(new Dimension(1936, 1056));
        driver.findElement(By.id("email")).sendKeys("t.s4@test.com");
        driver.findElement(By.id("password")).sendKeys("!Selenium4");
        driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
        driver.findElement(By.linkText("Warehouse")).click();
        driver.findElement(By.id("tipo_c")).click();
        driver.findElement(By.id("tipo_c")).sendKeys("grano");
        driver.findElement(By.id("quantita_c")).click();
        driver.findElement(By.id("quantita_c")).sendKeys("150");
        driver.findElement(By.cssSelector("form:nth-child(5) button")).click();
        driver.findElement(By.id("tipo_f")).click();
        driver.findElement(By.id("tipo_f")).sendKeys("gallinamicina");
        driver.findElement(By.id("quantita_f")).click();
        driver.findElement(By.id("quantita_f")).sendKeys("150");
        driver.findElement(By.cssSelector("form:nth-child(7) button")).click();
        driver.findElement(By.name("azione")).click();
        {
            WebElement dropdown = driver.findElement(By.name("azione"));
            dropdown.findElement(By.xpath("//option[. = 'remove']")).click();
        }
        driver.findElement(By.name("cambio")).click();
        driver.findElement(By.name("cambio")).sendKeys("150");
        driver.findElement(By.cssSelector(".cibo-display form:nth-child(4) button")).click();
        driver.findElement(By.cssSelector(".cibo-display li")).click();
        assertThat(driver.findElement(By.cssSelector(".cibo-display span:nth-child(1)")).getText(), is("grano"));
        driver.findElement(By.cssSelector(".farmaci-display label > input")).click();
        driver.findElement(By.cssSelector(".farmaci-display select")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector(".farmaci-display select"));
            dropdown.findElement(By.xpath("//option[. = 'remove']")).click();
        }
        driver.findElement(By.cssSelector(".farmaci-display label > input")).click();
        driver.findElement(By.cssSelector(".farmaci-display label > input")).sendKeys("150");
        driver.findElement(By.cssSelector(".farmaci-display form:nth-child(4) button")).click();
        driver.findElement(By.cssSelector(".farmaci-display li")).click();
        assertThat(driver.findElement(By.cssSelector(".farmaci-display span:nth-child(1)")).getText(), is("gallinamicina"));
        driver.findElement(By.cssSelector(".farmaci-title")).click();
        driver.findElement(By.cssSelector(".cibo-display form:nth-child(3) button")).click();
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    }
}

