package com.example.pollai.magazzino;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NotificaCarenzaScorteTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void notificaCarenzaScorte() {
        driver.get("http://localhost:8080/login-page");
        driver.manage().window().setSize(new Dimension(1936, 1056));
        driver.findElement(By.id("email")).sendKeys("t.s5@test.com");
        driver.findElement(By.id("password")).sendKeys("!Selenium5");
        driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
        driver.findElement(By.linkText("Warehouse")).click();
        driver.findElement(By.id("tipo_c")).click();
        driver.findElement(By.id("tipo_c")).sendKeys("Grano");
        driver.findElement(By.id("quantita_c")).sendKeys("600");
        driver.findElement(By.cssSelector("form:nth-child(5) button")).click();
        driver.findElement(By.cssSelector(".content-container")).click();
        assertThat(driver.findElement(By.cssSelector("span:nth-child(3)")).getText(), is("Our food supplies are enough"));
        driver.findElement(By.name("cambio")).click();
        driver.findElement(By.name("cambio")).sendKeys("250");
        driver.findElement(By.name("azione")).click();
        {
            WebElement dropdown = driver.findElement(By.name("azione"));
            dropdown.findElement(By.xpath("//option[. = 'remove']")).click();
        }
        driver.findElement(By.cssSelector("button:nth-child(5)")).click();
        driver.findElement(By.cssSelector(".content-container")).click();
        assertThat(driver.findElement(By.cssSelector("span:nth-child(3)")).getText(), is("We will soon run out of food supplies"));
        driver.findElement(By.name("azione")).click();
        {
            WebElement dropdown = driver.findElement(By.name("azione"));
            dropdown.findElement(By.xpath("//option[. = 'remove']")).click();
        }
        driver.findElement(By.name("cambio")).click();
        driver.findElement(By.name("cambio")).sendKeys("250");
        driver.findElement(By.cssSelector("button:nth-child(5)")).click();
        driver.findElement(By.cssSelector(".content-container")).click();
        assertThat(driver.findElement(By.cssSelector("span:nth-child(3)")).getText(), is("We are running out of food supplies"));
        driver.findElement(By.name("cambio")).click();
        driver.findElement(By.name("azione")).click();
        {
            WebElement dropdown = driver.findElement(By.name("azione"));
            dropdown.findElement(By.xpath("//option[. = 'remove']")).click();
        }
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
        driver.findElement(By.cssSelector(".content-container")).click();
        assertThat(driver.findElement(By.cssSelector("span:nth-child(3)")).getText(), is("We are running out of food supplies"));
        driver.findElement(By.cssSelector(".content-container")).click();
    }
}

