package com.example.pollai.salute;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PollAISaluteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void salutetestloggeduser() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1295, 687));
    //WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(1000));
    //WebElement element = wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Click here!")));
    //element.click();
    driver.findElement(By.linkText("Click here!")).click();
    driver.findElement(By.id("email")).sendKeys("g.elefante19@studenti.unisa.it");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("123");
    driver.findElement(By.cssSelector(".button-login")).click();
    driver.findElement(By.linkText("Health")).click();
    driver.findElement(By.cssSelector("li:nth-child(1) button")).click();
    driver.findElement(By.cssSelector("button:nth-child(6)")).click();
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    driver.findElement(By.cssSelector("li:nth-child(2) button")).click();
    driver.findElement(By.cssSelector("button:nth-child(6)")).click();
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".initials")).click();
    driver.findElement(By.cssSelector(".user-profile")).click();
    driver.findElement(By.cssSelector("p:nth-child(1)")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.findElement(By.cssSelector("img")).click();
  }

  @Test
  public void salutetestnewuser() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(550, 672));
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.linkText("Click here!")).click();
    driver.findElement(By.cssSelector("img")).click();
    driver.findElement(By.linkText("Choose Your Plan")).click();
    driver.findElement(By.cssSelector(".plan-box:nth-child(1) .subscribe-button")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("salute");
    driver.findElement(By.id("cognome")).click();
    driver.findElement(By.id("cognome")).sendKeys("test");
    driver.findElement(By.id("phoneNumber")).click();
    driver.findElement(By.id("phoneNumber")).sendKeys("12344532");
    driver.findElement(By.id("pIVA")).click();
    driver.findElement(By.id("pIVA")).sendKeys("IT" + String.valueOf(generateRandomNumber()));
    driver.findElement(By.cssSelector(".submit")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys(generateRandomEmail());
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("saluteTest123!");
    //driver.findElement(By.id("document")).click();
    driver.findElement(By.id("document")).sendKeys("C:\\Users\\ACER\\Downloads\\PD_sanremo_traccia (1).pdf");
    driver.findElement(By.cssSelector(".submit")).click();
    driver.findElement(By.linkText("Health")).click();
  }

  public static String generateRandomEmail() {
    // Define the characters to use in the email
    String characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    String domains = "gmail.com,yahoo.com,outlook.com,example.com";

    Random random = new Random();

    // Generate random local part (before @)
    int localPartLength = 8 + random.nextInt(5); // Random length between 8 and 12
    StringBuilder localPart = new StringBuilder();
    for (int i = 0; i < localPartLength; i++) {
      localPart.append(characters.charAt(random.nextInt(characters.length())));
    }

    // Pick a random domain
    String[] domainList = domains.split(",");
    String domain = domainList[random.nextInt(domainList.length)];

    // Combine local part and domain
    return localPart + "@" + domain;
  }


  public static String generateRandomNumber() {
    Random random = new Random();
    StringBuilder randomNumber = new StringBuilder();

    // Generate 11 random digits
    for (int i = 0; i < 11; i++) {
      int digit = random.nextInt(10); // Random digit between 0 and 9
      randomNumber.append(digit);
    }
    return randomNumber.toString();
  }

}

