package com.example.pollai.pollaio;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

public class AccessoPollaioTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }


    @Test
    public void accessoPollaio() {
        driver.get("http://localhost:8080/login-page");
        driver.manage().window().setSize(new Dimension(1936, 1056));

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("carmilla2@gmail.com");
        driver.findElement(By.id("password")).sendKeys("Carmilla2?");
        driver.findElement(By.id("password")).sendKeys(Keys.ENTER);

        WebElement chickenCoopLink = wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Chicken coop")));
        chickenCoopLink.click();

        wait.until(ExpectedConditions.urlContains("/accesso-pollaio"));

        driver.findElement(By.cssSelector("p:nth-child(1)")).click();
        driver.findElement(By.cssSelector(".content-container")).click();
        driver.findElement(By.linkText("Logout")).click();
    }



}


