package com.example.pollai.pollaio;


// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;


import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

public class InserimentoPesoGallinaTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }


    @Test
    public void inserimentoPesoGallina() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(786, 816));

        driver.findElement(By.linkText("Click here!")).click();
        driver.findElement(By.id("email")).sendKeys("carmilla2@gmail.com");
        driver.findElement(By.id("password")).sendKeys("Carmilla2?");
        driver.findElement(By.cssSelector(".button-login")).click();

        driver.findElement(By.linkText("Chicken coop")).click();

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

        WebElement razzaField = driver.findElement(By.name("razza"));
        wait.until(ExpectedConditions.visibilityOf(razzaField));
        razzaField.sendKeys("Livorno");

        WebElement etaField = driver.findElement(By.name("eta"));
        wait.until(ExpectedConditions.visibilityOf(etaField));
        etaField.sendKeys("5");

        WebElement pesoField = driver.findElement(By.name("peso"));
        wait.until(ExpectedConditions.visibilityOf(pesoField));
        pesoField.sendKeys("2,500"); //peso errato

        driver.findElement(By.cssSelector("button[type='submit']")).click();

        pesoField = driver.findElement(By.name("peso"));
        wait.until(ExpectedConditions.visibilityOf(pesoField));
        pesoField.clear();
        pesoField.sendKeys("2500");  // Correggi il peso

        razzaField = driver.findElement(By.name("razza"));
        etaField = driver.findElement(By.name("eta"));

        wait.until(ExpectedConditions.visibilityOf(razzaField));
        razzaField.clear();
        razzaField.sendKeys("Livorno");

        wait.until(ExpectedConditions.visibilityOf(etaField));
        etaField.clear();
        etaField.sendKeys("5");

        driver.findElement(By.cssSelector("button[type='submit']")).click();

        driver.quit();
    }


}
